apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-bit-hec
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: fluent-bit-hec
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: splunk
        property: SPLUNK_HEC_TOKEN
