apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- postgres.yaml
- servicemonitor.yaml
- secretstore.yaml
- externalsecrets.yaml
- networkpolicies.yaml
- cart/
- payment/
- ads/

configMapGenerator:
- files:
  - init.sql=init.sql
  name: postgres-initdb

images:
- name: ads
  newName: ghcr.io/fkft/prod_arch_web-ads
  newTag: 1b2c4602f823409d45a6081ccd8716e8ca893a0b
- name: cart
  newName: ghcr.io/fkft/prod_arch_web-cart
  newTag: 1b2c4602f823409d45a6081ccd8716e8ca893a0b
- name: payment
  newName: ghcr.io/fkft/prod_arch_web-payment
  newTag: 1b2c4602f823409d45a6081ccd8716e8ca893a0b
- name: website
  newName: ghcr.io/fkft/prod_arch_web
  newTag: 1b2c4602f823409d45a6081ccd8716e8ca893a0b
