apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- postgres.yaml
- servicemonitor.yaml
- secretstore.yaml
- externalsecrets.yaml
- networkpolicies.yaml
- cart/
- payment/
- ads/

configMapGenerator:
- files:
  - init.sql=init.sql
  name: postgres-initdb

images:
- name: ads
  newName: ghcr.io/fkft/prod_arch_web-ads
  newTag: 178660c742793d5633bebe8e2308bca2e869b335
- name: cart
  newName: ghcr.io/fkft/prod_arch_web-cart
  newTag: 178660c742793d5633bebe8e2308bca2e869b335
- name: payment
  newName: ghcr.io/fkft/prod_arch_web-payment
  newTag: 178660c742793d5633bebe8e2308bca2e869b335
- name: website
  newName: ghcr.io/fkft/prod_arch_web
  newTag: 178660c742793d5633bebe8e2308bca2e869b335
