apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splunk-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: splunk-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: splunk
